#!/usr/bin/env bash
# Display active listening ports with PID and Program Name
echo "Active Internet connections (only servers)"
sudo netstat -tulnp | grep LISTEN || true
echo "Active UNIX domain sockets (only servers)"
sudo netstat -lxp || true
