#!/usr/bin/env bash
# This script configures the /etc/hosts file to modify DNS resolutions
sudo sed -i 's/^127.0.0.1\s*localhost$/127.0.0.2 localhost/' /etc/hosts
sudo sed -i '/facebook.com/d' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
