#!/usr/bin/env bash
# This script configures the /etc/hosts file to modify DNS resolutions
cp /etc/hosts /etc/hosts.bak
sudo sed -i "/localhost/d" /etc/hosts
sudo sed -i "/facebook.com/d" /etc/hosts
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
